export default[
    { "_id": "A101", "title": "Propulsion Assignment", "cid": "RS101", "points": "100",
     "description": "Submit a link to the landing page of your Web application running on Netlify.", "availableFrom": "2024-05-06", "availableUntil": "2024-05-16" },
    { "_id": "A102", "title": "Combustion Analysis", "cid": "RS101", "points": "100",
    "description": "Submit a link to the landing page of your Web application running on Netlify.", "availableFrom": "2024-05-06", "availableUntil": "2024-05-16" },
    { "_id": "A103", "title": "Nozzle Design Project", "cid": "RS101", "points": "100",
    "description": "Submit a link to the landing page of your Web application running on Netlify.", "availableFrom": "2024-05-06", "availableUntil": "2024-05-16"},
    { "_id": "A201", "title": "Aerodynamics Quiz", "cid": "RS102", "points": "100",
    "description": "Submit a link to the landing page of your Web application running on Netlify.", "availableFrom": "2024-05-06", "availableUntil": "2024-05-16" },
    { "_id": "A202", "title": "Flow Analysis", "cid": "RS102", "points": "100",
    "description": "Submit a link to the landing page of your Web application running on Netlify.", "availableFrom": "2024-05-06", "availableUntil": "2024-05-16"},
    { "_id": "A203", "title": "Heating Analysis", "cid": "RS102", "points": "100",
    "description": "Submit a link to the landing page of your Web application running on Netlify.", "availableFrom": "2024-05-06", "availableUntil": "2024-05-16" },
    { "_id": "A301", "title": "Structural Design Task", "cid": "RS103", "points": "100",
    "description": "Submit a link to the landing page of your Web application running on Netlify.", "availableFrom": "2024-05-06", "availableUntil": "2024-05-16" },
    { "_id": "A302", "title": "Orbital Calculations", "cid": "RS103", "points": "100",
    "description": "Submit a link to the landing page of your Web application running on Netlify.", "availableFrom": "2024-05-06", "availableUntil": "2024-05-16" },
    { "_id": "A303", "title": "Systems Engineering Exam", "cid": "RS103", "points": "100",
    "description": "Submit a link to the landing page of your Web application running on Netlify.", "availableFrom": "2024-05-06", "availableUntil": "2024-05-16" }
  ]